# Generated by Django 4.1.1 on 2022-09-07 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_rename_comment_review_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='text',
            new_name='comment',
        ),
    ]
