# Generated by Django 4.1.1 on 2022-09-14 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
